import {
  ArrowRight,
  BadgeCheck,
  Banknote,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  CircleDollarSign,
  Coins,
  GraduationCap,
  HandCoins,
  HeartHandshake,
  Landmark,
  Laptop,
  LineChart,
  LockKeyhole,
  Mail,
  Menu,
  MessageCircle,
  Phone,
  Search,
  ShieldCheck,
  Sparkles,
  Sprout,
  User,
  UserPlus,
  Users,
  WalletCards,
  X,
} from "lucide-react";

export const Icons = {
  arrowRight: ArrowRight,
  badgeCheck: BadgeCheck,
  banknote: Banknote,
  bookOpen: BookOpen,
  briefcase: BriefcaseBusiness,
  building: Building2,
  chart: ChartNoAxesCombined,
  check: Check,
  chevronDown: ChevronDown,
  circleDollar: CircleDollarSign,
  coins: Coins,
  graduationCap: GraduationCap,
  handCoins: HandCoins,
  heartHandshake: HeartHandshake,
  landmark: Landmark,
  laptop: Laptop,
  lineChart: LineChart,
  lock: LockKeyhole,
  mail: Mail,
  menu: Menu,
  message: MessageCircle,
  phone: Phone,
  search: Search,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  sprout: Sprout,
  user: User,
  userPlus: UserPlus,
  users: Users,
  walletCards: WalletCards,
  x: X,
};
