import {
  ArrowRight,
  BadgeCheck,
  Banknote,
  BookOpen,
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  CircleDollarSign,
  Coins,
  ClipboardCheck,
  FileText,
  GraduationCap,
  HandCoins,
  Home,
  Info,
  HeartHandshake,
  Landmark,
  Layers3,
  Laptop,
  LineChart,
  LockKeyhole,
  Mail,
  Menu,
  MessageCircle,
  Newspaper,
  Phone,
  Rocket,
  Route,
  Scale,
  Search,
  ShieldCheck,
  Sparkles,
  Sprout,
  Target,
  TrendingUp,
  User,
  UserPlus,
  Users,
  WalletCards,
  X,
} from "lucide-react";

export const Icons = {
  arrowRight: ArrowRight,
  badgeCheck: BadgeCheck,
  banknote: Banknote,
  bookOpen: BookOpen,
  bot: Bot,
  brain: BrainCircuit,
  briefcase: BriefcaseBusiness,
  building: Building2,
  chart: ChartNoAxesCombined,
  check: Check,
  chevronDown: ChevronDown,
  circleDollar: CircleDollarSign,
  coins: Coins,
  clipboardCheck: ClipboardCheck,
  fileText: FileText,
  graduationCap: GraduationCap,
  handCoins: HandCoins,
  home: Home,
  info: Info,
  heartHandshake: HeartHandshake,
  landmark: Landmark,
  layers: Layers3,
  laptop: Laptop,
  lineChart: LineChart,
  lock: LockKeyhole,
  mail: Mail,
  menu: Menu,
  message: MessageCircle,
  newspaper: Newspaper,
  phone: Phone,
  rocket: Rocket,
  route: Route,
  scale: Scale,
  search: Search,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  sprout: Sprout,
  target: Target,
  trendingUp: TrendingUp,
  user: User,
  userPlus: UserPlus,
  users: Users,
  walletCards: WalletCards,
  x: X,
};

export type IconName = keyof typeof Icons;
